const ACTION_TYPE = {
    MOUSE_CHANGE_XY: 'MOUSE_CHANGE_XY',
    MOUSE_CLICK_POSITION_XY: 'MOUSE_CLICK_POSITION_XY',
    MOUSE_DOUBLE_CLICK: 'MOUSE_DOUBLE_CLICK',
    UPDATE_USER: 'UPDATE_USER',
    
    FETCH_USER: 'FETCH_USER',
    FETCH_USER_FULFILLED: 'FETCH_USER_FULFILLED',
    CONNECT_USER: 'CONNECT_USER',
    CUBE_ROTATION: 'CUBE_ROTATION',
}

export default ACTION_TYPE;